
object Versions {

    object Core{
        const val KTX = "1.13.1"
        const val LIFECYLE_RUNTIME_KTX = "2.7.0"
        const val APP_COMPAT = "1.6.1"
        const val SPLASHSCREEN = "1.0.1"
    }

    object Compose{
        const val ACTIVITY_COMPOSE = "1.8.2"
        const val COMPOSE_BOM = "2024.02.01"
        const val COMPOSE_CONSTRAINT_LAYOUT = "1.0.1"
        const val HILT_COMPOSE_NAVIGATION = "1.1.0"
        const val COMPOSE_NAVIGATION = "2.7.6"
    }
    const val MATERIAL_ICONS = "1.6.0"
    const val MATERIAL_WINDOW_SIZE = "1.2.0"
    const val JUNIT = "4.13.2"
    const val KOTLIN_COMPILER_EXTENSION = "1.5.10"
    const val ANDROIDX_STARTUP = "1.1.1"
    const val DATASTORE = "1.0.0"
    const val WORKMANAGER = "2.9.0"
    const val ROOM = "2.6.1"
    const val HILT = "2.50"
    const val ANDROIDX_HILT = "1.1.0"
    const val PLAY_SERVICES_LOCATION = "21.0.1"
    const val GSON = "2.10.1"
    const val ACCOMPANIST = "0.34.0"
    const val APPCENTER = "5.0.4"
    const val RETROFIT = "2.9.0"
    const val OK_HTTP = "4.12.0"
    const val DATADOG = "2.5.1"
    const val DATADOG_PLUGIN = "1.12.0"
    const val EXOPLAYER = "2.19.1"
    const val ML_KIT = "17.2.0"
    const val KOTLINX_COROUTINES_GUAVA = "1.7.3"
    const val KOTLINX_COROUTINES = "1.7.3"
    const val CAMERA_X = "1.3.2"
    const val KTOR = "2.3.7"
    const val JSOUP = "1.17.2"
    const val ANDROIDX_EXT_JUNIT = "1.1.5"
    const val ROBOLECTRIC = "4.12.2"
    const val ANDROIDX_TEST = "1.5.0"
    const val ANDROIDX_TEST_RUNNER = "1.5.2"
    const val ANDROIDX_TEST_RULES = "1.5.0"
    const val COROUTINES_TEST = "1.7.3"
    const val MSAL = "5.4.0"
    const val OPEN_TELEMETRY = "1.34.1"
    const val JWT = "4.4.0"
    const val PROTOBUF_PROTOC = "3.25.2"
    const val PROTOBUF_LITE = "3.25.2"
    const val MOCKITO = "5.10.0"
    const val MOCKITO_KOTLIN = "5.2.1"
    const val ESPRESSO = "3.5.1"
    const val HIVEMQ_MQTT_CLIENT = "1.3.3"
    const val PUSHER = "2.2.1"
}